workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 30
    environment:
      vars:
        ANDROID_HOME: /opt/android-sdk
      java: 17
      android:
        image: latest
    scripts:
      - name: Set up Gradle wrapper permissions
        script: chmod +x gradlew
      - name: Build Debug APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - dinakaranthangavel@gmail.com
          
