workflows:
  android-build:
    name: Build Android APK
    max_build_duration: 30
    environment:
      vars:
        ANDROID_HOME: /opt/android-sdk
      java: 17
    scripts:
      - name: Build Debug APK
        script: ./gradlew || gradle assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
    publishing:
      email:
        recipients:
          - dinakaranthangavel@gmail.com
